
CREATE TABLE POCIAG
(
  ID INTEGER PRIMARY KEY NOT NULL,
  NAZWA_POCIAG VARCHAR(30),
  TYP_POCIAG VARCHAR(30),
  ILOSC_WAGON INTEGER,
  OPUZNIONY BIT,
  MIASTA VARCHAR(30),
  TADATA DATE,

  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT POCIAG_PK PRIMARY KEY (ID)
);


CREATE TABLE MIASTA
(
  ID INTEGER PRIMARY KEY NOT NULL,
  KRAJ VARCHAR(4),
  NAZWA_MIASTA VARCHAR(30),
  WSP_MIASTA VARCHAR(30),

  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT MIASTA_PK PRIMARY KEY (ID)
);

CREATE TABLE WAGONY
(
  ID INTEGER PRIMARY KEY NOT NULL,
  NUMER_W INTEGER,
  ILOSC_MIEJSC INTEGER,
  TYP_WAGON VARCHAR(30),

  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT WAGONY_PK PRIMARY KEY (ID)
);

CREATE TABLE PASAZER
(
  ID INTEGER PRIMARY KEY NOT NULL,
  IMIE VARCHAR(30),
  DRUGIE_IMIE VARCHAR(30),
  NAZWISKO VARCHAR(30),
  N_WAGON INTEGER,
  N_MIEJSCA INTEGER,
  KOSZT_BILETU DECIMAL,
  ULGA BIT,
  TYP_UGLI VARCHAR(30),
  M_STARTIMIE VARCHAR(30),
  M_KONCA IMIE VARCHAR(30),

  CREATED TIMESTAMP NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED TIMESTAMP NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT PASAZER_PK PRIMARY dbo.KEY (ID)
);


CREATE TABLE WAGONY_PASAZER
(
  ID INTEGER NOT NULL,
  ID_WAGONY INTEGER NOT NULL,
  ID_PASAZER INTEGER NOT NULL,
  MIEJSCE INTEGER,
  GODZINA_OD VARCHAR(4),
  GODZINA_DO VARCHAR(4),

  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT WAGONY_PASAZER_PK PRIMARY KEY (ID)
  CONSTRAINT FK_WAGONY_WP FOREIGN KEY (ID_WAGONY) REFERENCES WAGONY (ID),
  CONSTRAINT FK_PASAZER_WP FOREIGN KEY (ID_PASAZER) REFERENCES PASAZER (ID) 
);


CREATE TABLE POCIAG_PASAZER
(
  ID INTEGER NOT NULL,
  ID_POCIAG INTEGER NOT NULL,
  ID_PASAZER INTEGER NOT NULL,

  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT POCIAG_PASAZER_PK PRIMARY KEY (ID),
  CONSTRAINT FK_POCIAG_PP FOREIGN KEY (ID_POCIAG) REFERENCES POCIAG (ID),
  CONSTRAINT FK_PASAZER_PP FOREIGN KEY (ID_PASAZER) REFERENCES PASAZER (ID) 

);


CREATE TABLE POCIAG_MIASTA
(
  ID INTEGER NOT NULL,
  ID_POCIAG INTEGER NOT NULL,
  ID_MIASTA INTEGER NOT NULL,
  DWORZEC VARCHAR(30),
  PERON VARCHAR(15),
  TOR INTEGER,
  GODZINA_ODJAZDU VARCHAR(4),

  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT POCIAG_MIASTA_PK PRIMARY KEY (ID),
  CONSTRAINT FK_POCIAG_PM FOREIGN KEY (ID_POCIAG) REFERENCES POCIAG (ID),
  CONSTRAINT FK_MIASTA_PM FOREIGN KEY (ID_MIASTA) REFERENCES MIASTA (ID) 

);


CREATE TABLE POCIAG_WAGONY
(
  ID INTEGER NOT NULL,
  ID_POCIAG INTEGER NOT NULL,
  ID_WAGONY INTEGER NOT NULL,

  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT POCIAG_WAGONY_PK PRIMARY KEY (ID),
  CONSTRAINT FK_POCIAG_PW FOREIGN KEY (ID_POCIAG) REFERENCES POCIAG (ID),
  CONSTRAINT FK_WAGONY_PW FOREIGN KEY (ID_WAGONY) REFERENCES WAGONY (ID) 

);


CREATE TABLE BILET
(
  ID INTEGER PRIMARY KEY NOT NULL,
  ID_PASAZER INTEGER NOT NULL,
  ID_POCIAG INTEGER NOT NULL,
  ID_WAGONY INTEGER NOT NULL,
  NUMER_MIEJSCA INTEGER,
  NUMER_BILETU INTEGER,
  CODEQR VARBINARY(max),
  CENA INTEGER,
  

  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT PRACOWNIK_ZESPOL_PK PRIMARY KEY (ID),
  CONSTRAINT FK_PRACOWNIK_PS FOREIGN KEY (ID_PRACOWNIK) REFERENCES PRACOWNIK (ID),
  CONSTRAINT FK_ZESPOL_PS FOREIGN KEY (ID_ZESPOL) REFERENCES ZESPOL (ID) 
);

CREATE TABLE BILET_PASAZER
(
  ID INTEGER NOT NULL
  ID_PASAZER INTEGER NOT NULL,
  ID_BILET INTEGER NOT NULL,
  
  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT BILET_PASAZER_PK PRIMARY KEY (ID),
  CONSTRAINT FK_BILET_PB FOREIGN KEY (ID_BILET) REFERENCES BILET (ID),
  CONSTRAINT FK_PASAZER_PB FOREIGN KEY (ID_PASAZER) REFERENCES PASAZER (ID) 
);

CREATE TABLE BILET_POCIAG
(
  ID INTEGER NOT NULL
  ID_POCIAG INTEGER NOT NULL,
  ID_BILET INTEGER NOT NULL,
  
  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT BILET_POCIAG_PK PRIMARY KEY (ID),
  CONSTRAINT FK_BILET_PB FOREIGN KEY (ID_BILET) REFERENCES BILET (ID),
  CONSTRAINT FK_POCIAG_PB FOREIGN KEY (ID_POCIAG) REFERENCES POCIAG (ID) 
);

CREATE TABLE BILET_WAGONY
(
  ID INTEGER NOT NULL
  ID_WAGONY INTEGER NOT NULL,
  ID_BILET INTEGER NOT NULL,
  
  CREATED DATETIME2 NOT NULL,
  CREATEDBY VARCHAR(31) NOT NULL,
  MODIFIED DATETIME2 NOT NULL,
  MODIFIEDBY VARCHAR(31) NOT NULL,
  CONSTRAINT BILET_WAGONY_PK PRIMARY KEY (ID),
  CONSTRAINT FK_BILET_PB FOREIGN KEY (ID_BILET) REFERENCES BILET (ID),
  CONSTRAINT FK_WAGONY_PB FOREIGN KEY (ID_WAGONY) REFERENCES WAGONY (ID) 
);
